name: Build EarnApp Image on Weekly Schedule

on:
  schedule:
    - cron: '0 3 * * 1' # weekly, Mondays 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Extract EarnApp version
        id: version
        run: |
          wget -qO /tmp/install.sh https://cdn-earnapp.b-cdn.net/static/earnapp/install.sh
          VERSION=$(grep '^VERSION=' /tmp/install.sh | cut -d'"' -f2)
          if [ -z "$VERSION" ]; then
            echo "Failed to extract EarnApp version!"
            exit 1
          fi
          echo "EARNAPP_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/xterna/earnapp:cache
          cache-to: type=registry,ref=ghcr.io/xterna/earnapp:cache,mode=max
          pull: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: |
            ghcr.io/xterna/earnapp:${{ env.EARNAPP_VERSION }}
            ghcr.io/xterna/earnapp:latest
